### ISSUE TITLE
Ytdl command failed

### ISSUE THREAD

**Issue by AnggaR96s** [fdciabdul/InsideHeartz-WhatsApp-Bot#23]
os >>> Error: Command failed: ytdl https://youtu.be/K9jR4hSCbG4 -q highest -o mp4/K9jR4hSCbG4.mp4
usage: ytdl [-h] [-i] [-s]
            [-t {audio,video,normal,all} [{audio,video,normal,all} ...]]
            [-n N] [-b] [-a]
            url
ytdl: error: unrecognized arguments: -q highest -o mp4/K9jR4hSCbG4.mp4

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'ytdl https://youtu.be/K9jR4hSCbG4 -q highest -o mp4/K9jR4hSCbG4.mp4'
}

**Comment by fdciabdul** [comment]
npm i -g ytdl

**Comment by AnggaR96s** [comment]
> npm i -g ytdl

video id =  K9jR4hSCbG4
`info.length_seconds` will be removed in a near future release, use `info.videoDetails.lengthSeconds` instead.
`info.length_seconds` will be removed in a near future release, use `info.videoDetails.lengthSeconds` instead.
477

**Comment by fdciabdul** [comment]
tapi bisa kan ?

**Comment by AnggaR96s** [comment]
> tapi bisa kan ?

 `Tunggu sebentar kak .. Lagi di proses ☺`
Gitu doang

**Comment by insideheartz** [comment]
> > tapi bisa kan ?
> 
> `Tunggu sebentar kak .. Lagi di proses ☺`
> Gitu doang

keknya di ffmpegnya

**Comment by AnggaR96s** [comment]
> > > tapi bisa kan ?
> > 
> > 
> > `Tunggu sebentar kak .. Lagi di proses ☺`
> > Gitu doang
> 
> keknya di ffmpegnya

Iya knp?

**Comment by arif1713** [comment]
masalahnya apa ya ?
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module './user.js'
Require stack:
- /home/jok32/Music/InsideHeartz-WhatsApp-Bot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/jok32/Music/InsideHeartz-WhatsApp-Bot/index.js:10:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/jok32/Music/InsideHeartz-WhatsApp-Bot/index.js' ]
}
