### ISSUE TITLE
modules erorr

### ISSUE THREAD

**Issue by arif1713** [fdciabdul/InsideHeartz-WhatsApp-Bot#25]
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module './user.js'
Require stack:
- /home/jok32/Music/InsideHeartz-WhatsApp-Bot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/jok32/Music/InsideHeartz-WhatsApp-Bot/index.js:10:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/jok32/Music/InsideHeartz-WhatsApp-Bot/index.js' ]
}

**Comment by Auza39** [comment]
sama bang gimana ngatasinya

**Comment by fdciabdul** [comment]
udah fix , silahkan update ke versi terbaru

**Comment by arif1713** [comment]
masih error mas
D:\bot\InsideHeartz-WhatsApp-Bot>node index.js
D:\bot\InsideHeartz-WhatsApp-Bot\lib\cmd.js:48
exports.searchYoutube = searchYoutube;
                        ^

ReferenceError: searchYoutube is not defined
    at Object.<anonymous> (D:\bot\InsideHeartz-WhatsApp-Bot\lib\cmd.js:48:25)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\bot\InsideHeartz-WhatsApp-Bot\index.js:18:13)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)

**Comment by Auza39** [comment]
ini kenapa ya om :\Users\AzureUser>node index.js
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\AzureUser\index.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []

**Comment by fdciabdul** [comment]
> ini kenapa ya om :\Users\AzureUser>node index.js
> internal/modules/cjs/loader.js:968
> throw err;
> ^
> 
> Error: Cannot find module 'C:\Users\AzureUser\index.js'
> �[90m at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)�[39m
> �[90m at Function.Module._load (internal/modules/cjs/loader.js:841:27)�[39m
> �[90m at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)�[39m
> �[90m at internal/main/run_main_module.js:17:47�[39m {
> code: �[32m'MODULE_NOT_FOUND'�[39m,
> requireStack: []

script nya ditaro dimana

**Comment by andikidsss** [comment]
Hue malah gini

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '@open-wa/wa-automate'
Require stack:
- /storage/emulated/0/Download/yul/whatsapp-bot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/storage/emulated/0/Download/yul/whatsapp-bot/index.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/storage/emulated/0/Download/yul/whatsapp-bot/index.js' ]

**Comment by fdciabdul** [comment]
> Gue malah gini, ada yg faham salahnya dimna?
> 
> internal/modules/cjs/loader.js:883
> throw err;
> ^
> 
> Error: Cannot find module '@open-wa/wa-automate'
> Require stack:
> 
> * /storage/emulated/0/Download/yul/whatsapp-bot/index.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>   at Module.require (internal/modules/cjs/loader.js:952:19)
>   at require (internal/modules/cjs/helpers.js:88:18)
>   at Object. (/storage/emulated/0/Download/yul/whatsapp-bot/index.js:1:28)
>   at Module._compile (internal/modules/cjs/loader.js:1063:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>   at Module.load (internal/modules/cjs/loader.js:928:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/storage/emulated/0/Download/yul/whatsapp-bot/index.js' ]

gw gapake open-wa
