### ISSUE TITLE
erorr saat command !play 

### ISSUE THREAD

**Issue by benirabbny** [fdciabdul/InsideHeartz-WhatsApp-Bot#34]
pas command !play langsung stop kenapa ya
![image](https://user-images.githubusercontent.com/68042984/94396835-f7d65480-018c-11eb-8dc8-93dd592e9425.png)

**Comment by rebahanelite** [comment]
gaada file / foldernya itu bang, wkwkwk

**Comment by fdciabdul** [comment]
> pas command !play langsung stop kenapa ya
> ![image](https://user-images.githubusercontent.com/68042984/94396835-f7d65480-018c-11eb-8dc8-93dd592e9425.png)

lupa nambahin si zerotwo 😂

**Comment by ArugaZ** [comment]
undefined:1
<HTML><HEAD>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (C:\Users\ARGA\botwa\InsideHeartz-WhatsApp-Bot\index.js:905:20)
    at Request.self.callback (C:\Users\ARGA\botwa\InsideHeartz-WhatsApp-Bot\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\ARGA\botwa\InsideHeartz-WhatsApp-Bot\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\ARGA\botwa\InsideHeartz-WhatsApp-Bot\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)


ini dari sananya package request eror?

**Comment by fdciabdul** [comment]
@ArugaZ kayanya si iya , coba update aja

**Comment by benirabbny** [comment]
> > pas command !play langsung stop kenapa ya
> > ![image](https://user-images.githubusercontent.com/68042984/94396835-f7d65480-018c-11eb-8dc8-93dd592e9425.png)
> 
> lupa nambahin si zerotwo 😂

oke sip dah bisa thx
