### ISSUE TITLE
Error pada request

### ISSUE THREAD

**Issue by ArugaZ** [fdciabdul/InsideHeartz-WhatsApp-Bot#47]
(node:7720) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at Client.<anonymous> (C:\Users\ARGA\works\InsideHeartz-WhatsApp-Bot\index.js:1001:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

error pada request.get nya jadi pada command (!ptl1, !searchimage, dll) pada seperti diatas. solusi nya om, saya run di win 10

**Comment by fdciabdul** [comment]
di fitur apa

**Comment by ArugaZ** [comment]
> di fitur apa

!ptl1, !ptl2, !searchimage, !nama, !pasangan, !chord, !randomanime ini command yg tidak bisa pada masalah diatas

**Comment by fdciabdul** [comment]
> > di fitur apa
> 
> !ptl1, !ptl2, !searchimage, !nama, !pasangan, !chord, !randomanime ini command yg tidak bisa pada masalah diatas

gapernah si ngalamin ini , coba turunkan versi nodejs nya ke versi stable

**Comment by daenghunter** [comment]
@fdciabdul punyaku juga sama xixixi..


gmna nurunkan versi node js :v

**Comment by fdciabdul** [comment]
> @fdciabdul punyaku juga sama xixixi..
> 
> gmna nurunkan versi node js :v

mau ganti pake ini si https://github.com/googleapis/gaxios

**Comment by Hendra827** [comment]
Saya juga begitu
Pertama sebelum di tambah fitur msih bisa

**Comment by ArugaZ** [comment]
> Saya juga begitu
> Pertama sebelum di tambah fitur msih bisa

pada package request udh deprecated, harus ganti

**Comment by Hendra827** [comment]
> > Saya juga begitu
> > Pertama sebelum di tambah fitur msih bisa
> 
> pada package request udh deprecated, harus ganti

Gimana gantinya gan

**Comment by ArugaZ** [comment]
> > > Saya juga begitu
> > > Pertama sebelum di tambah fitur msih bisa
> > 
> > 
> > pada package request udh deprecated, harus ganti
> 
> Gimana gantinya gan

tungguin pemilik update aja gan, mau ganti package doi

**Comment by fdciabdul** [comment]
silahkan clone ulang , sudah di fix ya
