### ISSUE TITLE
error

### ISSUE THREAD

**Issue by tlsteven48** [fdciabdul/InsideHeartz-WhatsApp-Bot#6]
Debugger listening on ws://127.0.0.1:15454/0a611e9b-59a7-4701-a2d9-f118bade5740
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
(node:27299) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn C:/Program Files (x86)/Google/Chrome/Application/chrome.exe ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/agung/my-projects/wa-botcobacoba/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
    at ChildProcess.<anonymous> (/home/agung/my-projects/wa-botcobacoba/node_modules/puppeteer/lib/launcher/BrowserRunner.js:151:82)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:27299) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27299) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[ 16:05:28 ] Mqtt topic subscribed!

**Comment by fdciabdul** [comment]
pake linux atau windows ?

**Comment by tlsteven48** [comment]
pakai c9 di windows

**Comment by fdciabdul** [comment]
> pakai c9 di windows

gw sih gaterlalu paham sama cloud9 , tapi itu errornya karna chrome nya gakebaca 

coba cari letak path chrome nya dimana trus edit ExecutablePath nya

**Comment by tlsteven48** [comment]
biasanya di folder mana bang.?

**Comment by fdciabdul** [comment]
> biasanya di folder mana bang.?

coba di terminal 

```bash
which chrome
```

**Comment by nezpjct** [comment]
bang bikin tutor download nya pliss
